# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proto_consumo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_APP_debito(object):
    def setupUi(self, APP_debito):
        APP_debito.setObjectName("APP_debito")
        APP_debito.resize(750, 550)
        APP_debito.setMinimumSize(QtCore.QSize(750, 550))
        APP_debito.setMaximumSize(QtCore.QSize(750, 560))
        APP_debito.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        APP_debito.setFont(font)
        APP_debito.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(APP_debito)
        self.centralwidget.setObjectName("centralwidget")
        self.grupo1_frame = QtWidgets.QFrame(self.centralwidget)
        self.grupo1_frame.setGeometry(QtCore.QRect(0, 0, 801, 351))
        self.grupo1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grupo1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grupo1_frame.setObjectName("grupo1_frame")
        self.saldo_actual_label = QtWidgets.QLabel(self.grupo1_frame)
        self.saldo_actual_label.setGeometry(QtCore.QRect(260, 60, 201, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.saldo_actual_label.setFont(font)
        self.saldo_actual_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.saldo_actual_label.setObjectName("saldo_actual_label")
        self.r_saldo_act_label = QtWidgets.QLabel(self.grupo1_frame)
        self.r_saldo_act_label.setGeometry(QtCore.QRect(250, 110, 251, 81))
        font = QtGui.QFont()
        font.setFamily("GLYPHICONS Halflings")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.r_saldo_act_label.setFont(font)
        self.r_saldo_act_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r_saldo_act_label.setStyleSheet("color: rgb(0, 170, 0);")
        self.r_saldo_act_label.setText("")
        self.r_saldo_act_label.setScaledContents(True)
        self.r_saldo_act_label.setAlignment(QtCore.Qt.AlignCenter)
        self.r_saldo_act_label.setObjectName("r_saldo_act_label")
        self.uid_label = QtWidgets.QLabel(self.grupo1_frame)
        self.uid_label.setGeometry(QtCore.QRect(530, 20, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.uid_label.setFont(font)
        self.uid_label.setObjectName("uid_label")
        self.r_uid_label = QtWidgets.QLabel(self.grupo1_frame)
        self.r_uid_label.setGeometry(QtCore.QRect(610, 20, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.r_uid_label.setFont(font)
        self.r_uid_label.setStyleSheet("color: rgb(0, 85, 255);")
        self.r_uid_label.setText("")
        self.r_uid_label.setObjectName("r_uid_label")
        self.saldo_restante_label = QtWidgets.QLabel(self.grupo1_frame)
        self.saldo_restante_label.setGeometry(QtCore.QRect(260, 220, 191, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.saldo_restante_label.setFont(font)
        self.saldo_restante_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.saldo_restante_label.setScaledContents(True)
        self.saldo_restante_label.setAlignment(QtCore.Qt.AlignCenter)
        self.saldo_restante_label.setObjectName("saldo_restante_label")
        self.r_sald_rest_label = QtWidgets.QLabel(self.grupo1_frame)
        self.r_sald_rest_label.setEnabled(True)
        self.r_sald_rest_label.setGeometry(QtCore.QRect(250, 270, 251, 50))
        font = QtGui.QFont()
        font.setFamily("GLYPHICONS Halflings")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.r_sald_rest_label.setFont(font)
        self.r_sald_rest_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r_sald_rest_label.setStyleSheet("color: rgb(0, 170, 0);")
        self.r_sald_rest_label.setText("")
        self.r_sald_rest_label.setScaledContents(True)
        self.r_sald_rest_label.setAlignment(QtCore.Qt.AlignCenter)
        self.r_sald_rest_label.setObjectName("r_sald_rest_label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 370, 801, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(610, 70, 121, 27))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(120, 20))
        self.pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.aviso_label = QtWidgets.QLabel(self.frame)
        self.aviso_label.setGeometry(QtCore.QRect(20, 0, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.aviso_label.setFont(font)
        self.aviso_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.aviso_label.setText("")
        self.aviso_label.setAlignment(QtCore.Qt.AlignCenter)
        self.aviso_label.setObjectName("aviso_label")
        self.frame.raise_()
        self.grupo1_frame.raise_()
        APP_debito.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(APP_debito)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        APP_debito.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(APP_debito)
        self.statusbar.setObjectName("statusbar")
        APP_debito.setStatusBar(self.statusbar)
        self.actionDetener = QtWidgets.QAction(APP_debito)
        self.actionDetener.setObjectName("actionDetener")
        self.actionAyuda = QtWidgets.QAction(APP_debito)
        self.actionAyuda.setObjectName("actionAyuda")
        self.actionSalir = QtWidgets.QAction(APP_debito)
        self.actionSalir.setObjectName("actionSalir")
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionDetener)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionAyuda)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionSalir)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(APP_debito)
        QtCore.QMetaObject.connectSlotsByName(APP_debito)

    def retranslateUi(self, APP_debito):
        _translate = QtCore.QCoreApplication.translate
        APP_debito.setWindowTitle(_translate("APP_debito", "MainWindow"))
        self.saldo_actual_label.setText(_translate("APP_debito", "<html><head/><body><p align=\"center\"><span style=\" color:#005500;\">Su saldo actual:</span></p></body></html>"))
        self.uid_label.setText(_translate("APP_debito", "UID:"))
        self.saldo_restante_label.setText(_translate("APP_debito", "Saldo restante:"))
        self.pushButton.setText(_translate("APP_debito", "DETENER"))
        self.menuMenu.setTitle(_translate("APP_debito", "Menu"))
        self.actionDetener.setText(_translate("APP_debito", "Detener"))
        self.actionAyuda.setText(_translate("APP_debito", "Ayuda"))
        self.actionSalir.setText(_translate("APP_debito", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    APP_debito = QtWidgets.QMainWindow()
    ui = Ui_APP_debito()
    ui.setupUi(APP_debito)
    APP_debito.show()
    sys.exit(app.exec_())
